version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cobertura
  - codeowners
  - endregion
  - entites
  - hass
  - hassio
  - homeassistant
  - homekit
  - hvac
  - macaddress
  - gbit
  - cbar
  - mbar
  - quickboot
  - websockets
  - rgbw
  - rgbww
  - hacs
  - mireds
  - gbuttons
  - rrule
  - rtsp
  - sonarjs
  - cardassia
  - zeldaar
  - breen
  - mbit
  - datetime
  - kbit
  - postdata
  - ssdp
  - systype
  - tvshow
  - lcars
  - zeroconf
  - templow
  - partlycloudy
ignoreWords: []
import: []
